# Generated by Django 5.1 on 2024-08-08 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TariffPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Minutes', models.CharField(max_length=20)),
                ('SMS', models.CharField(max_length=20)),
                ('Gigabytes', models.CharField(max_length=20)),
                ('Price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Simcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IMEI', models.CharField(max_length=255)),
                ('PhoneNumber', models.CharField(max_length=255)),
                ('ClientName', models.CharField(max_length=100)),
                ('RegistrationDate', models.DateField()),
                ('RecordCreationTime', models.DateTimeField(auto_now_add=True)),
                ('RecordUpdateTime', models.DateTimeField(auto_now=True)),
                ('TariffPlan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SimcardAPI.tariffplan')),
            ],
        ),
    ]
